# Generated by NeuroStack
# Artifact: workflow/calc_workflow

"""
Graph-Based Workflow: calc_workflow
Adds two integers with the calculator agent

Auto-generated by the Graph Workflow Studio.
ADK Docs: https://adk.dev/graphs/routes/
          https://adk.dev/graphs/human-input/
"""
from __future__ import annotations
from dotenv import load_dotenv, find_dotenv
from google.adk import Agent, Workflow, Event, Context
import importlib.util as _ilu
import pathlib as _pl
_spec_agents_p_calc = _ilu.spec_from_file_location(
    'p_calc',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'p_calc' / 'agent.py',
)
_mod_agents_p_calc = _ilu.module_from_spec(_spec_agents_p_calc)
_spec_agents_p_calc.loader.exec_module(_mod_agents_p_calc)

p_calc = _mod_agents_p_calc.root_agent
from pydantic import BaseModel
from typing import Any
import os, re

load_dotenv(find_dotenv())


# ──────────────────────────────────────────────
# Pydantic Schemas
# ──────────────────────────────────────────────
# (No custom schemas)

# ──────────────────────────────────────────────
# Agent Definitions
# ──────────────────────────────────────────────
# (No agent nodes defined)

# ──────────────────────────────────────────────
# Join Nodes — Fan-in for parallel branches
# ──────────────────────────────────────────────
# (No join nodes)

# ──────────────────────────────────────────────
# Function Nodes — Plain Python (no LLM)
# ──────────────────────────────────────────────
# (No function nodes)

# ──────────────────────────────────────────────
# HITL Nodes — yield RequestInput(...) to pause for human input
# ──────────────────────────────────────────────
# (No HITL nodes)

# ──────────────────────────────────────────────
# Router Nodes — return Event(route=KEY) for conditional branching
# ──────────────────────────────────────────────
# (No router nodes)

# ──────────────────────────────────────────────
# Workflow Graph
# ──────────────────────────────────────────────
root_agent = Workflow(
    name="calc_workflow",
    edges=[
        ("START", p_calc),
        (p_calc,),  # → END
    ]
)
