# Generated by NeuroStack
# Vendored from platform origin: agent/writer_agent (upstream_version=platform)

from __future__ import annotations

from google.adk import Agent
from google.adk.tools import load_memory
from google.genai import types

import importlib.util as _ilu
import pathlib as _pl
_spec_rel_prompt = _ilu.spec_from_file_location(
    'prompt',
    _pl.Path(__file__).parent / 'prompt.py',
)
_mod_rel_prompt = _ilu.module_from_spec(_spec_rel_prompt)
_spec_rel_prompt.loader.exec_module(_mod_rel_prompt)

SYSTEM_PROMPT = _mod_rel_prompt.SYSTEM_PROMPT
def create_writer_agent() -> Agent:
    """Instantiate a standalone writer agent."""

    return Agent(
        name="writer_agent",
        model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
        description="Generates and refines documents on various topics, creating clear and well-structured content.",
        instruction=SYSTEM_PROMPT,
        tools=[load_memory],
        generate_content_config=types.GenerateContentConfig(
            safety_settings=[
                types.SafetySetting(
                    category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                    threshold=types.HarmBlockThreshold.OFF,
                ),
            ]
        ),
    )

writer_agent = create_writer_agent()

root_agent = writer_agent
