# Generated by NeuroStack
# Artifact: agent/temperature_agent


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

# No MCP servers configured
import pathlib
from google.adk.skills import load_skill_from_dir
from google.adk.tools.skill_toolset import SkillToolset



_skill_toolset = SkillToolset(
    skills=[
    load_skill_from_dir(pathlib.Path(__file__).parent.parent.parent / "skills" / "explain-conversion"),
    ],
)


# ============================================================================
# AGENT DEFINITION
# ============================================================================

temperature_agent = Agent(
    name="temperature_agent",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[
        _skill_toolset,

    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.3,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = temperature_agent
