# Generated by NeuroStack
# Vendored from platform origin: agent/p_calc (upstream_version=platform)

"""
simple calculator
"""

from google.adk.agents import LlmAgent
from google.adk.tools.function_tool import FunctionTool
from pathlib import Path
import sys
# Add the project root to the path (where modular_agents package is located)
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

# Import direct tools
import importlib.util as _ilu
import pathlib as _pl
_spec_tools_p_calculator_tools = _ilu.spec_from_file_location(
    'p_calculator_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'p_calculator_tools.py',
)
_mod_tools_p_calculator_tools = _ilu.module_from_spec(_spec_tools_p_calculator_tools)
_spec_tools_p_calculator_tools.loader.exec_module(_mod_tools_p_calculator_tools)

add_integers = _mod_tools_p_calculator_tools.add_integers

# Create p_calc agent with direct tools
# Note: API key should be set via environment variable GOOGLE_API_KEY
root_agent = LlmAgent(
    name="p_calc",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description="simple calculator",
    instruction="""a simple calculator to add two integers""",
    tools=[
        FunctionTool(func=add_integers),

    ],
)
