# Generated by NeuroStack
# Artifact: workflow/sample_worflow

"""
Workflow: sample_worflow
Description: Summary of the topic
Instructions: Summary of the topic
"""
from __future__ import annotations
from google.adk import Agent
from google.adk.tools import load_memory
from google.genai import types

import importlib.util as _ilu
import pathlib as _pl
_spec_agents_critic_agent = _ilu.spec_from_file_location(
    'critic_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'critic_agent' / 'agent.py',
)
_mod_agents_critic_agent = _ilu.module_from_spec(_spec_agents_critic_agent)
_spec_agents_critic_agent.loader.exec_module(_mod_agents_critic_agent)
_spec_agents_writer_agent = _ilu.spec_from_file_location(
    'writer_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'writer_agent' / 'agent.py',
)
_mod_agents_writer_agent = _ilu.module_from_spec(_spec_agents_writer_agent)
_spec_agents_writer_agent.loader.exec_module(_mod_agents_writer_agent)

critic_agent = _mod_agents_critic_agent.root_agent
writer_agent = _mod_agents_writer_agent.root_agent





root_agent = Agent(
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    name="sample_worflow",
    description="""Summary of the topic""",
    instruction="""Summary of the topic""",
    global_instruction="""Summary of the topic""",
    sub_agents=[critic_agent, writer_agent],
    generate_content_config=types.GenerateContentConfig(
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
    tools=[load_memory],
)
