# Generated by NeuroStack
# Artifact: agent/zz_ui_verify_1791197126

"""
System prompt for zz_ui_verify_1791197126.
"""

AGENT_DESCRIPTION = """
ui verification
"""

SYSTEM_PROMPT = """
You are a test agent.
"""
