# Generated by NeuroStack
# Artifact: agent/sample_agent

"""
System prompt for sample_agent.
"""

AGENT_DESCRIPTION = """
Summary for a gives topic 
"""

SYSTEM_PROMPT = """
Summary for a gives topic
"""
