# Generated by NeuroStack
# Artifact: mcp/calc_server.py

"""
Server wrapper for calc_server MCP using MCPToolset.
Auto-generated by API at runtime.
"""

import sys
import os
from pathlib import Path
from google.adk.tools.mcp_tool.mcp_toolset import MCPToolset, StdioConnectionParams
from mcp import StdioServerParameters
from dotenv import load_dotenv
load_dotenv()

AGENT_TIMEOUT = int(os.getenv("AGENT_TIMEOUT", "180"))


def create_mcp_server() -> MCPToolset:
    """Create and return the MCPToolset for the 'calc_server' MCP."""
    toolset_script_path = str((Path(__file__).parent / "calc_server_toolset.py").resolve())
    return MCPToolset(
        connection_params=StdioConnectionParams(
            server_params=StdioServerParameters(
                command=sys.executable,
                args=[toolset_script_path],
            ),
            timeout=AGENT_TIMEOUT,
        )
    )
