# Generated by NeuroStack
# Vendored from platform origin: mcp/calculator_server (upstream_version=platform)

"""Server wrapper for calculator MCP. Auto-generated."""
import sys, os
from pathlib import Path
from google.adk.tools.mcp_tool.mcp_toolset import StdioConnectionParams, MCPToolset
from mcp import StdioServerParameters

try:
    from dotenv import load_dotenv; load_dotenv()
except Exception:
    pass

AGENT_TIMEOUT = int(os.getenv("AGENT_TIMEOUT", "300"))

def create_mcp_server() -> MCPToolset:
    toolset_path = str((Path(__file__).parent / "calculator_toolset.py").resolve())
    return MCPToolset(
        connection_params=StdioConnectionParams(
            server_params=StdioServerParameters(command=sys.executable, args=[toolset_path]),
            timeout=AGENT_TIMEOUT,
        )
    )
