# Generated by NeuroStack
# Artifact: mcp/calc_server.py

"""
FastMCP Server for calc_server exposing selected tools.
Auto-generated by API at runtime.
"""

from mcp.server.fastmcp import FastMCP
from typing import Any, Dict, List, Optional

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_ppp_calculator_tools = _ilu.spec_from_file_location(
    'ppp_calculator_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'ppp_calculator_tools.py',
)
_mod_tools_ppp_calculator_tools = _ilu.module_from_spec(_spec_tools_ppp_calculator_tools)
_spec_tools_ppp_calculator_tools.loader.exec_module(_mod_tools_ppp_calculator_tools)

tool_add_integers = _mod_tools_ppp_calculator_tools.add_integers

mcp = FastMCP("calc_server")


@mcp.tool()
async def add_integers(num1: int, num2: int) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `add_integers`.
    Calls the `add_integers` tool from the `ppp_calculator_tools` tool module.
    """
    return tool_add_integers(num1=num1, num2=num2)


if __name__ == "__main__":
    mcp.run(transport="stdio")
