# Generated by NeuroStack
# Vendored from platform origin: mcp/web_search (upstream_version=platform)

"""
FastMCP Server for web_search exposing selected tools.
Auto-generated by API at runtime.
"""

import sys
from pathlib import Path
from mcp.server.fastmcp import FastMCP
from typing import Dict, Any


mcp = FastMCP("web_search")


import importlib.util as _ilu
import pathlib as _pl
_spec_tools_web_search_tools = _ilu.spec_from_file_location(
    'web_search_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'web_search_tools.py',
)
_mod_tools_web_search_tools = _ilu.module_from_spec(_spec_tools_web_search_tools)
_spec_tools_web_search_tools.loader.exec_module(_mod_tools_web_search_tools)

@mcp.tool()
async def web_search(query: str, num_results: int = 5) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `web_search`.
    Calls the underlying function defined in `modular_agents.tools.web_search_tools`.
    """
    tool_web_search = _mod_tools_web_search_tools.web_search
    return tool_web_search(query, num_results)


@mcp.tool()
async def web_fetch(url: str) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `web_fetch`.
    Calls the underlying function defined in `modular_agents.tools.web_search_tools`.
    """
    tool_web_fetch = _mod_tools_web_search_tools.web_fetch
    return tool_web_fetch(url)


if __name__ == "__main__":
    mcp.run(transport="stdio")

