# Generated by NeuroStack
# Artifact: tool/distance_tools.py

"""Distance conversion tools for the Google ADK.

Provides pure-Python functions for converting between distance units.
"""


def miles_to_km(miles: float) -> dict:
    """Convert miles to kilometres.
    
    Use this tool to convert a distance measurement from miles to kilometres
    using the standard conversion factor (1 mile = 1.60934 kilometres).
    
    Args:
        miles: The distance in miles. Accepts any numeric value.
    
    Returns:
        A dictionary with either:
        - {"status": "success", "result": <kilometres_value>} on success
        - {"status": "error", "error_message": "<error_description>"} on invalid input
    """
    try:
        # Validate input is numeric
        if not isinstance(miles, (int, float)):
            return {
                "status": "error",
                "error_message": f"Invalid input type: expected float or int, got {type(miles).__name__}"
            }
        
        # Perform conversion using standard factor
        kilometres = miles * 1.60934
        
        return {
            "status": "success",
            "result": kilometres
        }
    
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Conversion failed: {str(e)}"
        }
