# Generated by NeuroStack
# Vendored from platform origin: tool/find_dotenv (upstream_version=platform)

"""
Enhanced Database Management Tools - enhanced_database_tools.py

Advanced database management tools specifically designed for financial data storage
and retrieval. This module provides comprehensive CRUD operations, schema management,
and data validation for stock market data utilizing SQLAlchemy.

Generated on: 2025-01-15
Total tools: 7
"""

from typing import Dict, Any, List, Optional, Union
import os
import pandas as pd
import json
import datetime
from dotenv import load_dotenv, find_dotenv
from sqlalchemy import create_engine, text

load_dotenv(find_dotenv())

db_url_default = os.getenv("DATABASE_URL", "postgresql://postgres:adminpassword@localhost:5432/agent_factory")

# Engine Cache
_engines = {}

def get_engine(db_path: str = None):
    """Helper to get a PostgreSQL SQLAlchemy engine."""
    current_url = db_url_default
    if db_path and (db_path.startswith("postgresql://") or db_path.startswith("postgres://")):
        current_url = db_path
    if current_url not in _engines:
        _engines[current_url] = create_engine(current_url, pool_size=5, max_overflow=10)
    return _engines[current_url]


def create_stock_database(
    db_path: str,
    include_tables: str = None
) -> Dict[str, Any]:
    """
    Create a new PostgreSQL database with optimized schema for stock data.
    
    Args:
        db_path (str): Connection string or path for the database
        include_tables (str): Comma-separated list of table types to create (e.g., 'stocks,dividends,splits,metadata')
        
    Returns:
        Dict[str, Any]: Database creation status and schema information
    """
    try:
        if include_tables is None:
            include_tables_list = ['stocks', 'dividends', 'splits', 'metadata']
        else:
            include_tables_list = [table.strip() for table in include_tables.split(',')]
        
        engine = get_engine(db_path)
        tables_created = []
        
        with engine.begin() as conn:
            # Create stocks table
            if 'stocks' in include_tables_list:
                conn.execute(text('''
                    CREATE TABLE IF NOT EXISTS stocks (
                        id SERIAL PRIMARY KEY,
                        ticker TEXT NOT NULL,
                        date DATE NOT NULL,
                        open FLOAT,
                        high FLOAT,
                        low FLOAT,
                        close FLOAT,
                        adj_close FLOAT,
                        volume BIGINT,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        UNIQUE(ticker, date)
                    )
                '''))
                
                # Create indexes for performance
                conn.execute(text('CREATE INDEX IF NOT EXISTS idx_stocks_ticker ON stocks(ticker)'))
                conn.execute(text('CREATE INDEX IF NOT EXISTS idx_stocks_date ON stocks(date)'))
                
                tables_created.append('stocks')
            
            # Create dividends table
            if 'dividends' in include_tables_list:
                conn.execute(text('''
                    CREATE TABLE IF NOT EXISTS dividends (
                        id SERIAL PRIMARY KEY,
                        ticker TEXT NOT NULL,
                        date DATE NOT NULL,
                        dividend_amount FLOAT NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        UNIQUE(ticker, date)
                    )
                '''))
                
                tables_created.append('dividends')
            
            # Create stock splits table
            if 'splits' in include_tables_list:
                conn.execute(text('''
                    CREATE TABLE IF NOT EXISTS stock_splits (
                        id SERIAL PRIMARY KEY,
                        ticker TEXT NOT NULL,
                        date DATE NOT NULL,
                        split_ratio FLOAT NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        UNIQUE(ticker, date)
                    )
                '''))
                
                tables_created.append('stock_splits')
            
            # Create metadata table
            if 'metadata' in include_tables_list:
                conn.execute(text('''
                    CREATE TABLE IF NOT EXISTS stock_metadata (
                        id SERIAL PRIMARY KEY,
                        ticker TEXT NOT NULL UNIQUE,
                        company_name TEXT,
                        sector TEXT,
                        industry TEXT,
                        currency TEXT DEFAULT 'USD',
                        market_cap FLOAT,
                        last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        data_source TEXT,
                        additional_info TEXT
                    )
                '''))
                
                tables_created.append('stock_metadata')
            
            # Create database info table
            conn.execute(text('''
                CREATE TABLE IF NOT EXISTS database_info (
                    id SERIAL PRIMARY KEY,
                    db_version TEXT DEFAULT '1.0',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    last_backup TIMESTAMP,
                    total_records INTEGER DEFAULT 0
                )
            '''))
            
            # Insert initial database info (using ON CONFLICT for Postgres)
            conn.execute(text('''
                INSERT INTO database_info (db_version, created_at, total_records)
                VALUES ('1.0', CURRENT_TIMESTAMP, 0)
                ON CONFLICT DO NOTHING
            '''))
        
        return {
            "success": True,
            "message": f"Database tables created successfully",
            "data": {
                "database_url": engine.url.render_as_string(hide_password=True),
                "tables_created": tables_created,
                "creation_time": datetime.datetime.now().isoformat()
            }
        }
        
    except Exception as e:
        return {
            "success": False,
            "message": f"Error creating database: {str(e)}",
            "data": None
        }


def insert_stock_data(
    db_path: str,
    ticker: str,
    stock_data: List[Dict[str, Any]],
    update_metadata: bool = True
) -> Dict[str, Any]:
    """
    Insert stock price data into the database with validation and deduplication.
    
    Args:
        db_path (str): Connection string or path for the PostgreSQL database
        ticker (str): Stock ticker symbol
        stock_data (List[Dict]): List of stock data dictionaries with OHLCV data
        update_metadata (bool): Whether to update metadata table
        
    Returns:
        Dict[str, Any]: Insertion results with statistics
    """
    try:
        engine = get_engine(db_path)
        inserted_count = 0
        skipped_count = 0
        
        with engine.begin() as conn:
            for data_point in stock_data:
                try:
                    # Extract data with validation
                    date = data_point.get('Date') or data_point.get('date')
                    if isinstance(date, str):
                        date = pd.to_datetime(date).strftime('%Y-%m-%d')
                    
                    open_price = data_point.get('Open') or data_point.get('open')
                    high_price = data_point.get('High') or data_point.get('high')
                    low_price = data_point.get('Low') or data_point.get('low')
                    close_price = data_point.get('Close') or data_point.get('close')
                    adj_close = data_point.get('Adj Close') or data_point.get('adj_close') or close_price
                    volume = data_point.get('Volume') or data_point.get('volume')
                    
                    # Validate required fields
                    if not all([date, open_price, high_price, low_price, close_price]):
                        skipped_count += 1
                        continue
                    
                    # Use UPSERT (INSERT ... ON CONFLICT)
                    result = conn.execute(text('''
                        INSERT INTO stocks 
                        (ticker, date, open, high, low, close, adj_close, volume, updated_at)
                        VALUES (:ticker, :date, :open, :high, :low, :close, :adj_close, :volume, CURRENT_TIMESTAMP)
                        ON CONFLICT (ticker, date) DO UPDATE SET
                            open = EXCLUDED.open,
                            high = EXCLUDED.high,
                            low = EXCLUDED.low,
                            close = EXCLUDED.close,
                            adj_close = EXCLUDED.adj_close,
                            volume = EXCLUDED.volume,
                            updated_at = CURRENT_TIMESTAMP
                    '''), {
                        "ticker": ticker,
                        "date": date,
                        "open": open_price,
                        "high": high_price,
                        "low": low_price,
                        "close": close_price,
                        "adj_close": adj_close,
                        "volume": volume
                    })
                    
                    if result.rowcount > 0:
                        inserted_count += 1
                    
                except Exception as e:
                    skipped_count += 1
                    continue
            
            # Update metadata if requested
            if update_metadata:
                conn.execute(text('''
                    INSERT INTO stock_metadata (ticker, last_updated, data_source)
                    VALUES (:ticker, CURRENT_TIMESTAMP, 'Manual Insert')
                    ON CONFLICT (ticker) DO UPDATE SET
                        last_updated = CURRENT_TIMESTAMP,
                        data_source = 'Manual Insert'
                '''), {"ticker": ticker})
        
        return {
            "success": True,
            "message": f"Stock data processed for {ticker}",
            "data": {
                "ticker": ticker,
                "inserted": inserted_count,
                "updated": 0, # UPSERT merged count
                "skipped": skipped_count,
                "total_processed": len(stock_data),
                "database_path": db_path
            }
        }
        
    except Exception as e:
        return {
            "success": False,
            "message": f"Error inserting stock data: {str(e)}",
            "data": None
        }


def update_stock_data(
    db_path: str,
    ticker: str,
    date: str,
    update_fields: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Update existing stock data records.
    
    Args:
        db_path (str): Connection string or path for the PostgreSQL database
        ticker (str): Stock ticker symbol
        date (str): Date of the record to update (YYYY-MM-DD)
        update_fields (Dict): Fields to update with new values
        
    Returns:
        Dict[str, Any]: Update operation results
    """
    try:
        engine = get_engine(db_path)
        
        with engine.begin() as conn:
            # Validate that record exists
            result = conn.execute(
                text('SELECT COUNT(*) FROM stocks WHERE ticker = :ticker AND date = :date'),
                {"ticker": ticker, "date": date}
            )
            if result.scalar() == 0:
                return {
                    "success": False,
                    "message": f"No record found for {ticker} on {date}",
                    "data": None
                }
            
            # Build update query
            valid_fields = ['open', 'high', 'low', 'close', 'adj_close', 'volume']
            update_parts = []
            params = {"ticker": ticker, "date": date}
            
            for field, value in update_fields.items():
                if field in valid_fields:
                    update_parts.append(f"{field} = :{field}")
                    params[field] = value
            
            if not update_parts:
                return {
                    "success": False,
                    "message": "No valid fields to update",
                    "data": None
                }
            
            # Add updated_at timestamp
            update_parts.append("updated_at = CURRENT_TIMESTAMP")
            
            query = f"UPDATE stocks SET {', '.join(update_parts)} WHERE ticker = :ticker AND date = :date"
            update_result = conn.execute(text(query), params)
            rows_affected = update_result.rowcount
            
        return {
            "success": True,
            "message": f"Successfully updated {ticker} data for {date}",
            "data": {
                "ticker": ticker,
                "date": date,
                "updated_fields": list(update_fields.keys()),
                "rows_affected": rows_affected
            }
        }
        
    except Exception as e:
        return {
            "success": False,
            "message": f"Error updating stock data: {str(e)}",
            "data": None
        }


def delete_stock_data(
    db_path: str,
    ticker: str = None,
    date_from: str = None,
    date_to: str = None,
    confirm: bool = False
) -> Dict[str, Any]:
    """
    Delete stock data records based on criteria.
    
    Args:
        db_path (str): Connection string or path for the PostgreSQL database
        ticker (str): Specific ticker to delete (optional)
        date_from (str): Delete records from this date (YYYY-MM-DD)
        date_to (str): Delete records up to this date (YYYY-MM-DD)
        confirm (bool): Must be True to execute deletion
        
    Returns:
        Dict[str, Any]: Deletion operation results
    """
    try:
        if not confirm:
            return {
                "success": False,
                "message": "Deletion not confirmed. Set confirm=True to proceed.",
                "data": None
            }
        
        engine = get_engine(db_path)
        
        with engine.begin() as conn:
            # Build delete query
            where_conditions = []
            params = {}
            
            if ticker:
                where_conditions.append("ticker = :ticker")
                params["ticker"] = ticker
            
            if date_from:
                where_conditions.append("date >= :date_from")
                params["date_from"] = date_from
            
            if date_to:
                where_conditions.append("date <= :date_to")
                params["date_to"] = date_to
            
            if not where_conditions:
                return {
                    "success": False,
                    "message": "No deletion criteria specified. This would delete all data.",
                    "data": None
                }
            
            where_clause = " AND ".join(where_conditions)
            
            # Count records to be deleted
            count_result = conn.execute(text(f"SELECT COUNT(*) FROM stocks WHERE {where_clause}"), params)
            records_to_delete = count_result.scalar()
            
            if records_to_delete == 0:
                return {
                    "success": True,
                    "message": "No records found matching criteria",
                    "data": {"deleted_count": 0}
                }
            
            # Execute deletion
            delete_result = conn.execute(text(f"DELETE FROM stocks WHERE {where_clause}"), params)
            deleted_count = delete_result.rowcount
            
        return {
            "success": True,
            "message": f"Successfully deleted {deleted_count} records",
            "data": {
                "deleted_count": deleted_count,
                "criteria": {
                    "ticker": ticker,
                    "date_from": date_from,
                    "date_to": date_to
                }
            }
        }
        
    except Exception as e:
        return {
            "success": False,
            "message": f"Error deleting stock data: {str(e)}",
            "data": None
        }


def query_stock_data(
    db_path: str,
    ticker: str = None,
    date_from: str = None,
    date_to: str = None,
    columns: str = None,
    limit: int = None,
    order_by: str = "date DESC"
) -> Dict[str, Any]:
    """
    Advanced query for stock data with filtering and sorting.
    
    Args:
        db_path (str): Connection string or path for the PostgreSQL database
        ticker (str): Filter by ticker symbol
        date_from (str): Filter from this date (YYYY-MM-DD)
        date_to (str): Filter to this date (YYYY-MM-DD)
        columns (str): Comma-separated list of columns to return (e.g., 'ticker,date,close')
        limit (int): Maximum number of records to return
        order_by (str): Order by clause (default: "date DESC")
        
    Returns:
        Dict[str, Any]: Query results with metadata
    """
    try:
        engine = get_engine(db_path)
        
        # Build query
        if columns:
            select_columns = ", ".join([col.strip() for col in columns.split(',')])
        else:
            select_columns = "*"
        
        where_conditions = []
        params = {}
        
        if ticker:
            where_conditions.append("ticker = :ticker")
            params["ticker"] = ticker
        
        if date_from:
            where_conditions.append("date >= :date_from")
            params["date_from"] = date_from
        
        if date_to:
            where_conditions.append("date <= :date_to")
            params["date_to"] = date_to
        
        query = f"SELECT {select_columns} FROM stocks"
        if where_conditions:
            query += " WHERE " + " AND ".join(where_conditions)
        
        if order_by:
            # Validate order_by slightly to prevent basic injection
            order_by_clean = " ".join([part.strip() for part in order_by.split() if part.strip()])
            query += f" ORDER BY {order_by_clean}"
        
        if limit:
            query += f" LIMIT :limit"
            params["limit"] = limit
        
        with engine.connect() as conn:
            # Execute query
            result = conn.execute(text(query), params)
            column_names = list(result.keys())
            
            # Fetch results and convert to list of dictionaries
            data_records = [dict(row._mapping) for row in result]
            
            # Get additional statistics
            count_query = "SELECT COUNT(*) FROM stocks"
            if where_conditions:
                count_query += " WHERE " + " AND ".join(where_conditions)
            total_matching = conn.execute(text(count_query), params).scalar()
            
        return {
            "success": True,
            "message": f"Query executed successfully. Found {len(data_records)} records",
            "data": {
                "records": data_records,
                "total_records": len(data_records),
                "total_matching": total_matching,
                "columns": column_names,
                "query_parameters": {
                    "ticker": ticker,
                    "date_from": date_from,
                    "date_to": date_to,
                    "limit": limit,
                    "order_by": order_by
                }
            }
        }
        
    except Exception as e:
        return {
            "success": False,
            "message": f"Error querying stock data: {str(e)}",
            "data": None
        }


def backup_database(
    db_path: str,
    backup_path: str = None,
    include_timestamp: bool = True
) -> Dict[str, Any]:
    """
    Create a backup of the stock database.
    
    Args:
        db_path (str): Path to the source database
        backup_path (str): Path for the backup (optional)
        include_timestamp (bool): Include timestamp in backup filename
        
    Returns:
        Dict[str, Any]: Backup operation results
    """
    try:
        return {
            "success": False,
            "message": "Backup via file copy is not supported for PostgreSQL. Please use 'pg_dump' for database backups.",
            "data": None
        }
        
    except Exception as e:
        return {
            "success": False,
            "message": f"Error: {str(e)}",
            "data": None
        }


def get_database_stats(db_path: str) -> Dict[str, Any]:
    """
    Get comprehensive statistics about the stock database.
    
    Args:
        db_path (str): Connection string or path for the PostgreSQL database
        
    Returns:
        Dict[str, Any]: Database statistics and information
    """
    try:
        engine = get_engine(db_path)
        
        stats = {
            "database_info": {
                "url": engine.url.render_as_string(hide_password=True),
                "type": "PostgreSQL"
            },
            "tables": {},
            "stock_data": {}
        }
        
        with engine.connect() as conn:
            # Get table information from information_schema
            tables_result = conn.execute(text("SELECT table_name FROM information_schema.tables WHERE table_schema='public'"))
            tables = [row[0] for row in tables_result]
            
            for table_name in tables:
                row_count = conn.execute(text(f'SELECT COUNT(*) FROM "{table_name}"')).scalar()
                stats["tables"][table_name] = {
                    "row_count": row_count
                }
            
            # Get stock-specific statistics
            if "stocks" in tables:
                total_records = conn.execute(text("SELECT COUNT(*) FROM stocks")).scalar()
                unique_tickers = conn.execute(text("SELECT COUNT(DISTINCT ticker) FROM stocks")).scalar()
                
                # Date range
                date_range_result = conn.execute(text("SELECT MIN(date), MAX(date) FROM stocks")).fetchone()
                
                # Records per ticker
                ticker_stats_result = conn.execute(text("""
                    SELECT ticker, COUNT(*) as count, MIN(date) as first_date, MAX(date) as last_date
                    FROM stocks 
                    GROUP BY ticker 
                    ORDER BY count DESC
                """))
                ticker_stats = ticker_stats_result.fetchall()
                
                stats["stock_data"] = {
                    "total_records": total_records,
                    "unique_tickers": unique_tickers,
                    "date_range": {
                        "earliest": str(date_range_result[0]) if date_range_result[0] else None,
                        "latest": str(date_range_result[1]) if date_range_result[1] else None
                    },
                    "ticker_breakdown": [
                        {
                            "ticker": row[0],
                            "record_count": row[1],
                            "first_date": str(row[2]) if row[2] else None,
                            "last_date": str(row[3]) if row[3] else None
                        }
                        for row in ticker_stats
                    ]
                }
        
        return {
            "success": True,
            "message": "Database statistics retrieved successfully",
            "data": stats
        }
        
    except Exception as e:
        return {
            "success": False,
            "message": f"Error retrieving database statistics: {str(e)}",
            "data": None
        }