# Generated by NeuroStack
# Vendored from platform origin: tool/add_integers (upstream_version=platform)

"""
Generated Tools - p_calculator_tools.py

Auto-generated tools created by the Tool Generator.
Generated on: 2024-10-27 03:37:00
Total tools: 1
"""

from typing import Dict, Any

def add_integers(num1: int, num2: int) -> Dict[str, Any]:
    """
    Adds two integers and returns the sum.

    Args:
        num1 (int): The first integer.
        num2 (int): The second integer.

    Returns:
        Dict[str, Any]: A dictionary containing the success status, message, and the sum of the two integers.
                       Example: {"success": True, "message": "Sum calculated successfully.", "data": {"sum": 5}}
                       If an error occurs, success will be False and the message will contain the error.
    """
    try:
        sum_result = num1 + num2
        return {
            "success": True,
            "message": "Sum calculated successfully.",
            "data": {"sum": sum_result}
        }
    except TypeError:
        return {
            "success": False,
            "message": "Error: Both inputs must be integers.",
            "data": {}
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error: {str(e)}",
            "data": {}
        }
