# Generated by NeuroStack
# Artifact: tool/temperature_tools.py

from typing import Dict, Any

def convert_temperature(value: float, unit: str) -> Dict[str, Any]:
    """
    Converts a temperature value between Celsius and Fahrenheit.

    Args:
        value (float): The numerical temperature value to be converted.
        unit (str): The current unit of the temperature. Must be 'celsius' or 'fahrenheit' (case-insensitive).

    Returns:
        Dict[str, Any]: A dictionary containing the success status, a message, and the conversion result.
                        If successful, 'data' will contain 'original_value', 'original_unit',
                        'converted_value', and 'converted_unit'.
                        If unsuccessful, 'message' will describe the error.
    """
    try:
        if not isinstance(value, (int, float)):
            raise TypeError("Temperature value must be a number (integer or float).")
        if not isinstance(unit, str):
            raise TypeError("Unit must be a string.")

        normalized_unit = unit.lower().strip()

        if normalized_unit not in ['celsius', 'fahrenheit']:
            raise ValueError(f"Invalid unit '{unit}'. Unit must be 'celsius' or 'fahrenheit'.")

        converted_value: float
        converted_unit: str

        if normalized_unit == 'celsius':
            converted_value = (value * 9/5) + 32
            converted_unit = 'fahrenheit'
        else:  # normalized_unit == 'fahrenheit'
            converted_value = (value - 32) * 5/9
            converted_unit = 'celsius'

        return {
            "success": True,
            "message": f"Successfully converted {value}°{unit} to {converted_value:.2f}°{converted_unit}.",
            "data": {
                "original_value": value,
                "original_unit": unit,
                "converted_value": round(converted_value, 2), # Round to 2 decimal places for readability
                "converted_unit": converted_unit
            }
        }

    except ValueError as ve:
        return {
            "success": False,
            "message": f"Input validation error: {str(ve)}"
        }
    except TypeError as te:
        return {
            "success": False,
            "message": f"Input type error: {str(te)}"
        }
    except Exception as e:
        # Catch any unexpected errors during calculation
        return {
            "success": False,
            "message": f"An unexpected error occurred during temperature conversion: {str(e)}"
        }