# Generated by NeuroStack
# Artifact: tool/unit_tools.py

"""Unit conversion tools for the ADK framework.

This module provides unit conversion functions for common measurement conversions.
"""


def km_to_miles(km: float) -> dict:
    """Convert kilometres to miles.
    
    Use this tool when you need to convert a distance measurement from kilometres
    to miles using the standard conversion factor (1 km = 0.621371 miles).
    
    Args:
        km: Distance in kilometres (must be a non-negative number)
    
    Returns:
        A dictionary with status and result:
        - On success: {"status": "success", "result": {"miles": float, "km": float}}
        - On error: {"status": "error", "error_message": str}
    """
    try:
        # Validate input type
        if not isinstance(km, (int, float)):
            return {
                "status": "error",
                "error_message": f"Input must be a number, got {type(km).__name__}"
            }
        
        # Validate input range
        if km < 0:
            return {
                "status": "error",
                "error_message": "Distance cannot be negative"
            }
        
        # Perform conversion using standard conversion factor
        # 1 kilometre = 0.621371 miles
        miles = km * 0.621371
        
        return {
            "status": "success",
            "result": {
                "miles": miles,
                "km": km
            }
        }
    
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Unexpected error during conversion: {str(e)}"
        }
