# Generated by NeuroStack
# Vendored from platform origin: tool/web_search_tools (upstream_version=platform)

"""
Web Search & Fetch Tools - web_search_tools.py

Tools for web searching and fetching content from web pages.
Uses LangSearch API for reliable web search.
"""

import os
import re
import requests
import json
import logging
from datetime import datetime, timezone
from typing import Dict, Any, List, Optional
from bs4 import BeautifulSoup
from dotenv import load_dotenv


# Load environment variables
load_dotenv()

logger = logging.getLogger(__name__)

# Check for LangSearch API key
LANGSEARCH_API_KEY = os.getenv("LANGSEARCH_API_KEY", "")
LANGSEARCH_API_AVAILABLE = bool(LANGSEARCH_API_KEY)

if not LANGSEARCH_API_AVAILABLE:
    logger.warning("LANGSEARCH_API_KEY not found in environment variables. Web search will not work.")


def clean_html_text(html: str) -> str:
    """Extract clean text from HTML."""
    try:
        soup = BeautifulSoup(html, 'html.parser')
        # Remove script and style elements
        for script in soup(["script", "style"]):
            script.decompose()
        # Get text and clean it
        text = soup.get_text()
        # Clean up whitespace
        lines = (line.strip() for line in text.splitlines())
        chunks = (phrase.strip() for line in lines for phrase in line.split("  "))
        text = ' '.join(chunk for chunk in chunks if chunk)
        return text
    except Exception:
        # Fallback to simple regex if BeautifulSoup fails
        text = re.sub(r'<[^>]+>', '', html)
        text = re.sub(r'\s+', ' ', text)
        return text.strip()


def web_search(query: str, num_results: int = 5) -> Dict[str, Any]:
    """
    Search the web for information about a product or topic.
    
    Uses LangSearch API for web search. Requires LANGSEARCH_API_KEY in .env file.
    
    Args:
        query: Search query (e.g., "Sony WH-1000XM5 reviews")
        num_results: Number of search results to return (default: 5, max: 20)
    
    Returns:
        Dictionary with search results including titles, URLs, and snippets
    """
    # Limit num_results to reasonable range
    num_results = min(max(1, num_results), 20)
    
    logger.info(f"Searching web for: {query} (requesting {num_results} results)")
    
    # Check if LangSearch API key is available
    if not LANGSEARCH_API_AVAILABLE:
        return {
            "success": False,
            "error": "LANGSEARCH_API_KEY not found in environment variables. Please add it to your .env file. Get your API key from https://langsearch.com/api-keys",
            "query": query,
            "results": []
        }
    
    # Use LangSearch API
    try:
        logger.info("Searching with LangSearch API...")
        langsearch_url = "https://api.langsearch.com/v1/web-search"
        headers = {
            'Authorization': f'Bearer {LANGSEARCH_API_KEY}',
            'Content-Type': 'application/json'
        }
        payload = {
            'query': query,
            'freshness': 'noLimit',  # Options: 'oneDay', 'oneWeek', 'oneMonth', 'oneYear', 'noLimit'
            'summary': True,
            'count': num_results
        }
        
        response = requests.post(langsearch_url, headers=headers, json=payload, timeout=30)
        response.raise_for_status()
        
        response_data = response.json()
        results = []
        
        # LangSearch API wraps response in {code, log_id, msg, data}
        # The actual search results are in data.webPages.value
        if response_data.get('code') != 200:
            error_msg = response_data.get('msg', 'Unknown error')
            logger.error(f"LangSearch API returned error code {response_data.get('code')}: {error_msg}")
            return {
                "success": False,
                "error": f"LangSearch API error: {error_msg}",
                "query": query,
                "results": []
            }
        
        # Extract the data field which contains the search results
        data = response_data.get('data', {})
        
        # Parse LangSearch response format - results are in data.webPages.value
        web_pages = data.get('webPages', {}).get('value', [])
        
        logger.info(f"LangSearch API response structure: {list(response_data.keys())}")
        logger.info(f"Found {len(web_pages)} items in response")
        
        for item in web_pages[:num_results]:
            # Try multiple field name variations
            title = item.get('name') or item.get('title') or item.get('headline') or ''
            url = item.get('url') or item.get('link') or item.get('href') or ''
            snippet = item.get('snippet') or item.get('description') or item.get('body') or item.get('abstract') or ''
            
            if title and url:
                results.append({
                    "title": title,
                    "url": url,
                    "snippet": snippet
                })
        
        logger.info(f"Found {len(results)} results using LangSearch API")
        
        if results:
            return {
                "success": True,
                "query": query,
                "results": results,
                "total_results": len(results),
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "method": "langsearch_api"
            }
        else:
            # Log the response for debugging
            logger.warning(f"LangSearch API returned no results. Response keys: {list(data.keys())}")
            logger.debug(f"Full response: {json.dumps(data, indent=2)[:500]}")
            return {
                "success": False,
                "error": f"LangSearch API returned no results. Response structure: {list(data.keys())}",
                "query": query,
                "results": [],
                "method": "langsearch_api"
            }
            
    except requests.RequestException as e:
        logger.error(f"LangSearch API request failed for query '{query}': {e}")
        return {
            "success": False,
            "error": f"LangSearch API request failed: {str(e)}",
            "query": query,
            "results": []
        }
    except Exception as e:
        logger.error(f"LangSearch API search failed for query '{query}': {e}", exc_info=True)
        return {
            "success": False,
            "error": f"LangSearch API search failed: {str(e)}",
            "query": query,
            "results": []
        }


def web_fetch(url: str) -> Dict[str, Any]:
    """
    Fetch and extract content from a web page.
    
    Args:
        url: URL of the webpage to fetch
    
    Returns:
        Dictionary with page content, title, and extracted text
    """
    logger.info(f"Fetching content from URL: {url}")
    
    try:
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.5',
            'Accept-Encoding': 'gzip, deflate',
            'Connection': 'keep-alive',
        }
        
        response = requests.get(url, headers=headers, timeout=15)
        response.raise_for_status()
        
        # Extract content
        html = response.text
        clean_text = clean_html_text(html)
        
        # Extract title
        soup = BeautifulSoup(html, 'html.parser')
        title = soup.find('title')
        title_text = title.get_text(strip=True) if title else "No title found"
        
        logger.info(f"Successfully fetched content from {url} (title: {title_text[:50]}...)")
        
        return {
            "success": True,
            "url": url,
            "title": title_text,
            "content": clean_text[:10000],  # Limit content length
            "full_content_length": len(clean_text),
            "timestamp": datetime.now(timezone.utc).isoformat()
        }
        
    except requests.RequestException as e:
        logger.error(f"Failed to fetch URL '{url}': {e}")
        return {
            "success": False,
            "error": f"Failed to fetch URL: {str(e)}",
            "url": url
        }
    except Exception as e:
        logger.error(f"Unexpected error fetching page '{url}': {e}", exc_info=True)
        return {
            "success": False,
            "error": f"Unexpected error fetching page: {str(e)}",
            "url": url
        }

