# Generated by NeuroStack
# Artifact: agent/zz_verify_1791196139

"""
System prompt for zz_verify_1791196139.
"""

AGENT_DESCRIPTION = """
verification agent
"""

SYSTEM_PROMPT = """
You are a test agent.
"""
