# Generated by NeuroStack
# Artifact: agent/zz_mcp_verify_1791197243


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_calculator_server = _ilu.spec_from_file_location(
    'calculator_server',
    _pl.Path(__file__).parent.parent.parent / 'mcp_servers' / 'internal' / 'calculator_server.py',
)
_mod_calculator_server = _ilu.module_from_spec(_spec_calculator_server)
_spec_calculator_server.loader.exec_module(_mod_calculator_server)
calculator_server = _mod_calculator_server.create_mcp_server
_spec_tools_enhanced_database_tools = _ilu.spec_from_file_location(
    'enhanced_database_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'enhanced_database_tools.py',
)
_mod_tools_enhanced_database_tools = _ilu.module_from_spec(_spec_tools_enhanced_database_tools)
_spec_tools_enhanced_database_tools.loader.exec_module(_mod_tools_enhanced_database_tools)
find_dotenv = _mod_tools_enhanced_database_tools.find_dotenv





# ============================================================================
# AGENT DEFINITION
# ============================================================================

zz_mcp_verify_1791197243 = Agent(
    name="zz_mcp_verify_1791197243",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[

        calculator_server(),
        find_dotenv,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = zz_mcp_verify_1791197243
